import fs from 'node:fs'
import { FAMILIES } from './families.mjs'
import { TYPE_BY_ID } from './types.mjs'
import { RATE, RANK_LABEL, BALL, singleThrowRate, cumulativeRate, displayLabel, starRating } from './capture.mjs'
import { encounterInfo, WILD_WEIGHT, ENCOUNTER_TUNING, ENCOUNTER_LOCK } from './wildEncounter.mjs'

const L = []; const w = (s = '') => L.push(s)

w('# 野生の出現と捕獲の設計')
w()
w('> 捕獲の数式・演出・野生出現テーブル・rank軸・エンカウント固定ルールの正本。')
w('> `01-catch-and-evolution-design.md` と `06-battle-and-progression-design.md` は本書を参照する。')
w()
w('## 0. 要約')
w()
w('| 項目 | 決定 |')
w('|---|---|')
w('| 捕獲方式 | **方式Aに一本化**（勝利→捕獲フェーズ→わ→最大3投）。HP残量・状態異常による補正は無し |')
w('| 捕獲式 | `P = (a/255)^(3/4)`、`a = min(255, rate × ball倍率)`。HP項は使わない |')
w('| 「かならずつかまる」表現 | **にじのわ 以外には使わない**（3投累積でも100%にはならない） |')
w('| rankの役割 | **捕獲のしにくさだけ**を表す軸。野生に出るか／進化専用か／一回限定かは別軸で判定 |')
w('| 一回限定遭遇 | 単体系列5体のみ（rank=legendの13体全部ではない） |')
w('| 野生出現プール | legend rank は含まない（進化専用・一回限定のどちらかであるため） |')
w('| 未捕獲補正 | 未登録種は出現重み×1.5、3匹以上捕獲済みの種は×0.6 |')
w('| エンカウント固定 | 遭遇は **RESOLVED になるまで同じ encounterId を保持**。逃走・敗北・画面離脱では再抽選されない |')
w()
w('---')
w()

// ===== 1. 捕獲の数式 =====
w('## 1. 捕獲の数式（方式Aのみ）')
w()
w('```')
w('a = min(255, rate × ball倍率)')
w('P（1投） = (a / 255)^(3/4)')
w('P（3投累積） = 1 − (1 − P)^3')
w('```')
w()
w('この簡約形は、参考にした旧来式の4段階サブ判定と同じ最終成功確率になる')
w('（a = 10/45/90/135/180/200/254 の7点で元式と検算済み）。**ここで述べているのは確率計算の由来のみで、視覚演出の仕様ではない。**')
w()
w('旧方式Bで使っていたHP残量の補正項')
w('（`(3×HPmax − 2×HPcur) / (3×HPmax)`）は「戦闘中に捕獲する」方式用であり、本作では使わない。')
w('方式Aでは捕獲フェーズに入る時点で敵は必ずHP0（たおしている）なので、HP項は意味を持たない。撤廃した。')
w()
w('| ランク | rate | ほしのわ×1 | ぎんのわ×1.5 | きんのわ×2 | にじのわ |')
w('|---|---|---|---|---|---|')
for (const [rankKey, rate] of Object.entries(RATE)) {
  const row = ['star', 'silver', 'gold', 'rainbow'].map((bk) => {
    const p1 = singleThrowRate(rate, bk)
    return `1投${(p1 * 100).toFixed(0)}%`
  })
  w(`| ${RANK_LABEL[rankKey]} | ${rate} | ${row.join(' | ')} |`)
}
w()
w('### 3投累積（誇張表現の禁止）')
w()
w('> ふつう×ほしのわでも厳密な100%ではない。')
w('> 1投成功率は83.34%、3投累積は**約99.54%**。したがって「かならず」と表示しない。')
w()
w('| ランク | ほしのわ 3投累積 | ぎんのわ 3投累積 | きんのわ 3投累積 | にじのわ |')
w('|---|---|---|---|---|')
for (const [rankKey, rate] of Object.entries(RATE)) {
  const row = ['star', 'silver', 'gold', 'rainbow'].map((bk) => {
    const p3 = cumulativeRate(rate, bk)
    return `${(p3 * 100).toFixed(2)}%`
  })
  w(`| ${RANK_LABEL[rankKey]} | ${row.join(' | ')} |`)
}
w()
w('**「かならずつかまる」「100%」と言えるのは にじのわ だけ。** それ以外は画面でも')
w('「ほとんど つかまる」「つかまえやすい」「つかまえにくい」のような相対表現にとどめ、')
w('数字を見せる場合も小数点まで正直に出す（丸めて100%と表示しない）。')
w()
w('### 表示ラベル（UIでの見せ方）')
w()
w('| 3投累積 | 表示 | ★の目安 |')
w('|---|---|---|')
for (const p of [0.99, 0.85, 0.6, 0.3, 0.1]) {
  w(`| ${(p*100).toFixed(0)}% | ${displayLabel(p)} | ${starRating(p)} |`)
}
w()
w('### 視覚演出（確率計算とは分離）')
w()
w('- 画面上の主役は**4つの星が順に点灯して輪が完成する**こと。')
w('- 成功時は4つ点灯後に輪が虹色に閉じる。')
w('- 失敗時は途中まで点灯した星が散り、輪がほどける。')
w('- 「わ」が4回物理的に揺れることは必須仕様にしない。')
w('- 内部で段階的なサブ判定を用いる場合でも、それをそのまま物理アニメーション回数へ結びつけない。')
w('- UI詳細は `03-screens-catch-and-raise.md`、横断原則は `08-gameplay-state-spec.md` §10 を優先する。')
w()
w('---')
w()

// ===== 2. 救済しない方針 =====
w('## 2. 捕獲の救済は入れない')
w()
w('「3回逃げられたら次は必ず成功」のような隠し救済は入れない。')
w('低確率で3投とも失敗すること自体は、')
w()
w('- 「次はきんのわを使おう」')
w('- 「にじのわ はこの子まで取っておこう」')
w('- 「もう少し勉強してわ を増やそう」')
w()
w('という動機になるため、価値として残す。ここを甘くすると、わ を選ぶ意味そのものが薄れる。')
w()
w('---')
w()

// ===== 3. rank軸の分離 =====
w('## 3. rank・野生出現・一回限定を別の軸にする')
w()
w('rank=legend（13体）には、通常の3段階系列の最終進化形')
w('（進化すれば何度でも入手できる）が9体含まれるため、「legend=固定の1回きり」と')
w('説明しない。')
w()
w('rank は **捕獲のしにくさだけ**の軸として使い、以下は系列の形から別に判定する。')
w()
w('| 軸 | 値 | 判定方法 |')
w('|---|---|---|')
w('| rank | ふつう／めずらしい／とてもめずらしい／でんせつ | データで直接指定（捕獲式の rate に使う） |')
w('| pool（出会い方） | wild／evolutionOnly／event | 系列内の位置（第1〜中間形態＝wild／最終形態＝evolutionOnly／単体系列＝event）から自動判定 |')
w('| repeat（何度でも入手できるか） | unlimited／once | pool=event（単体系列）だけが once |')
w('| bossGated | true／false | pool=event（単体系列）だけが true |')
w()
{
  const counts = { wild: 0, evolutionOnly: 0, event: 0 }
  const legendNonEvent = []
  FAMILIES.forEach((f) => f.members.forEach((m, i) => {
    const info = encounterInfo(f, i + 1)
    counts[info.pool]++
    if (m.rank === 'legend' && info.pool !== 'event') legendNonEvent.push(m.name)
  }))
  w(`実データでの内訳: wild ${counts.wild}体 / evolutionOnly ${counts.evolutionOnly}体 / event ${counts.event}体`)
  w()
  w(`rank=legend（13体）のうち、実際に一回限定なのは ${13 - legendNonEvent.length}体だけ。`)
  w(`残り${legendNonEvent.length}体（${legendNonEvent.join('、')}）は、進化すれば何度でも入手できる`)
  w('（evolutionOnly＝最終形態のため野生には出ないが、捕獲→育成→進化で誰でも到達できる）。')
}
w()
w('この分離により、「legend=激レア」という直感は保ったまま、')
w('「でも進化で手に入る子はちゃんと手に入る」を両立できる。')
w()
w('---')
w()

// ===== 4. 野生出現テーブル =====
w('## 4. 野生出現テーブル')
w()
w('### 出現の重み（rankベース）')
w()
w('| rank | 重み |')
w('|---|---|')
for (const [k, v] of Object.entries(WILD_WEIGHT)) w(`| ${RANK_LABEL[k]} | ${v} |`)
w('| でんせつ | （野生プールに含まれない。§3参照） |')
w()
w('エリア内の「wild」個体（＝非最終形態）を対象に、上の重みで抽選する。')
w('同じエリア内でも、ふつうランクが圧倒的に出やすく、とてもめずらしいはごくまれ、という体感になる。')
w()
w('### 未捕獲補正・連続抑制')
w()
w('| ルール | 値 |')
w('|---|---|')
w(`| 未登録種の重みボーナス | ×${ENCOUNTER_TUNING.uncaughtBonusMult} |`)
w(`| 3匹以上捕獲済みの種の重みペナルティ | ×${ENCOUNTER_TUNING.caughtPenaltyMult}（0にはしない＝厳選目的の再訪も許す） |`)
w(`| 直前と同じ種の連続出現 | 次の1回だけ出現プールから除外 |`)
w()
w('図鑑を埋めたい子には自然と未登録種が多く出て、埋まった後は「同じ子ばかり」になりにくい。')
w()
w('### エンカウント固定ルール（不正対策の核心）')
w()
w('> **何が問題だったか。** 「負けてもチケット消費なし」×「敗北すると敵が再抽選される」の組み合わせは、')
w('> 「レアが出るまでわざと負ける／わざと逃げる」を許してしまう抜け道になる。')
w()
w('遭遇した個体は、以下のいずれかまで**固定**する。')
w()
w('| できごと | 次の遭遇 |')
w('|---|---|')
w(`| 敵HPを0にして「たおした！」 | ${ENCOUNTER_LOCK.onEnemyDefeated === 'capturePhaseThenResolve' ? '**同じ encounterId の捕獲フェーズへ**。捕獲成功/3投失敗でRESOLVED後、次回だけ新しい抽選' : ''} |`)
w(`| 3投とも失敗して「にげられた」 | ${ENCOUNTER_LOCK.onCaptureFail3 === 'reroll' ? '新しい抽選' : ''} |`)
w(`| 全滅してHP全快した | ${ENCOUNTER_LOCK.onPlayerLosesHp0 === 'sameEncounterContinues' ? '**同じ相手のまま**（再抽選されない）' : ''} |`)
w(`| 「にげる」を選んで戦わずに離脱 | ${ENCOUNTER_LOCK.onPlayerFlees === 'sameEncounterContinues' ? '**同じ相手のまま**（再抽選されない）' : ''} |`)
w()
w('**結果として**: わざと負けても同じ相手と戦い直すだけで得しない。')
w('「にげる」を選んでも同じ相手が残るため、レア厳選の近道にはならない。')
w('隠しペナルティを追加せず、**構造だけで抜け道を塞ぐ**方針にした。')
w()
w('---')
w()

// ===== 5. ボス・イベント遭遇 =====
w('## 5. ボス・イベント遭遇')
w()
w('| 種別 | 対象 | 遭遇条件 | 捕獲 |')
w('|---|---|---|---|')
w('| エリアボス | 各エリア1体（4体） | 学習進行12pt かつ異なるskill 2つ以上（詳細は `08-gameplay-state-spec.md` / `AREA_BOSS_UNLOCK`） | 倒すと物語イベントとして仲間になる（捕獲判定なし） |')
w('| 単体系列（5体） | ユグドラシア・ホシラディア・ガイオドール・メテオルド・シラユキヒメ | 物語の節目で1回だけ遭遇 | 専用の捕獲演出（にじのわ相当の確定入手、または専用イベント） |')
w()
w('単体系列はそもそも「野生で何度も出る」対象ではないため、通常の出現テーブル（§4）には含めない。')
w()
w('---')
w()
w('## 6. この文書の数値の出どころ')
w()
w('```bash')
w('node scripts/capture.mjs       # 捕獲の1投／3投累積成功率')
w('node scripts/wildEncounter.mjs # 野生出現プールの分類・rank軸の分離')
w('node scripts/check2.mjs        # 捕獲・野生出現を含む横断検証')
w('node scripts/gen-wild-md.mjs   # この文書を再生成')
w('```')
w()

fs.writeFileSync(new URL('../07-wild-encounter-and-capture-design.md', import.meta.url), L.join('\n'))
console.log('07-wild-encounter-and-capture-design.md:', L.join('\n').length, 'bytes /', L.length, 'lines')
