from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'needle not found in {path}: {old[:160]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')


# Only relocated wild encounters need their area gate rewritten.
# Evolution trials, bosses and special challenges keep the canonical gates generated by the runtime master.
replace_once(
    'src/game/worldProgression.js',
    "  if (meta.area > 1 && meta.area <= 4 && !['event', 'ex'].includes(stage.kind)) next.areaGateBossId = `a${meta.area - 1}-boss`",
    "  if (stage.kind === 'wild' && meta.area !== Number(stage.area) && meta.area > 1 && meta.area <= 4) next.areaGateBossId = `a${meta.area - 1}-boss`"
)

# Test helpers now clear the same adventure-area wild pool that the engine uses.
replace_once(
    'tests/runtime-completion.test.js',
    "  const wild = STAGES.filter((stage) => stage.area === area && stage.kind === 'wild')",
    "  const wild = STAGES.filter((stage) => (stage.adventureArea || stage.area) === area && stage.kind === 'wild')"
)
replace_once(
    'tests/runtime-completion.test.js',
    "  const areaWild = STAGES.filter((stage) => stage.area === 1 && stage.kind === 'wild')",
    "  const areaWild = STAGES.filter((stage) => (stage.adventureArea || stage.area) === 1 && stage.kind === 'wild')"
)
