from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'needle not found in {path}: {old[:160]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')


# Only relocated wild encounters need their area gate rewritten.
# Evolution trials, bosses and special challenges keep the canonical gates generated by the runtime master.
replace_once(
    'src/game/worldProgression.js',
    "  if (meta.area > 1 && meta.area <= 4 && !['event', 'ex'].includes(stage.kind)) next.areaGateBossId = `a${meta.area - 1}-boss`",
    "  if (stage.kind === 'wild' && meta.area !== Number(stage.area) && meta.area > 1 && meta.area <= 4) next.areaGateBossId = `a${meta.area - 1}-boss`"
)

# Test helpers now clear the same adventure-area wild pool that the engine uses.
replace_once(
    'tests/runtime-completion.test.js',
    "  const wild = STAGES.filter((stage) => stage.area === area && stage.kind === 'wild')",
    "  const wild = STAGES.filter((stage) => (stage.adventureArea || stage.area) === area && stage.kind === 'wild')"
)
replace_once(
    'tests/runtime-completion.test.js',
    "  const areaWild = STAGES.filter((stage) => stage.area === 1 && stage.kind === 'wild')",
    "  const areaWild = STAGES.filter((stage) => (stage.adventureArea || stage.area) === 1 && stage.kind === 'wild')"
)

# Fix the memo closing generated by the large patch before Vite parses JSX.
replace_once(
    'src/game/GameScreens.jsx',
    "  }), [filteredStages, dailyMode, today, game, cleared])",
    "  }, [filteredStages, dailyMode, today, game, cleared])"
)

# The new level floor can change which deterministic enemy turn hits. The refund test is about
# loss/refund idempotence, not a particular RNG seed, so find a deterministic seed that produces a loss.
replace_once(
    'tests/game.test.js',
    """  const battle = structuredClone(started.battle)\n  battle.partyHp[battle.activeInstanceId] = 1\n  const result = useMove(started.game, battle, 'm004-stable')\n  assert.equal(result.battle.status, 'lost')\n  assert.equal(result.battle.ticketRefunded, true)\n  assert.equal(availableTicketCount(result.game, day), 1)\n  const cleared = clearFinishedBattle(result.game, { today: day })\n""",
    """  let result = null\n  for (let seed = 0; seed < 200 && !result; seed += 1) {\n    const battle = structuredClone(started.battle)\n    battle.partyHp[battle.activeInstanceId] = 1\n    battle.rngSeed = `loss-refund-${seed}`\n    const candidate = useMove(started.game, battle, 'm004-stable')\n    if (candidate.battle.status === 'lost') result = candidate\n  }\n  assert.ok(result, 'a deterministic enemy-hit seed should produce a loss')\n  assert.equal(result.battle.ticketRefunded, true)\n  assert.equal(availableTicketCount(result.game, day), 1)\n  const cleared = clearFinishedBattle(result.game, { today: day })\n"""
)
